#!/usr/bin/env bash
case "${BASH_SOURCE}" in
*/*) pushd "${BASH_SOURCE%/*}" &>/dev/null ;; # Enter the current directory
*) pushd . &>/dev/null ;; # This seems like duplicate work but we need to match the popd later
esac

function bu_activate_impl() 
{
local force=false
case "$*" in
*f*)
    force=true
    ;;
esac

case "$*" in
*e*)
    BU_SOURCE_IS_FORCE="$force" source ./bu_examples_entrypoint.sh
    ;;
*t*)
    BU_SOURCE_IS_FORCE="$force" source ./bu_test_entrypoint.sh
    ;;
*)
    BU_SOURCE_IS_FORCE="$force" source ./bu_entrypoint.sh
    ;;
esac
popd &>/dev/null
}

bu_activate_impl "$@"


